### ISSUE TITLE
Create a summary sheet of dandisets

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/DANDIArchiveShowcase#1]
- [ ] create script to access Dandi API to query current dandisets
- [x] generate a markdown file with one line for each with 
    - dandiset id
    - link to main dandiset page
    - number of files/size
    - number of nwb files
- [x] Add summary at top of page with summary statistics & date generated
- [x] commit latest markdown file

**Comment by pgleeson** [comment]
https://github.com/openworm/WormsenseLab_ASH/blob/main/test_data/make_readme.py

**Comment by sanjayankur31** [comment]
https://pynwb.readthedocs.io/en/stable/validation.html

**Comment by pgleeson** [comment]
Closing this and can create specific issues for updates to the readmes.
