### ISSUE TITLE
CI run failed

### ISSUE THREAD

**Issue by anhknguyen96** [OpenSourceBrain/DANDIArchiveShowcase#25]
Debugging log [here](https://github.com/OpenSourceBrain/DANDIArchiveShowcase/actions/runs/3162701984/jobs/5159892964#step:7:1190). Seems like a package dependency issue, I'll look further into this when I have time.

**Comment by anhknguyen96** [comment]
another fail, debugging log [here](https://github.com/OpenSourceBrain/DANDIArchiveShowcase/actions/runs/3162701984/jobs/5346276967). This time it manages to install Python dependencies, but failed (timeout?) while trying to datalad install dandiset 108 and its zarr subdatasets. There have been several issues for the zarr subdatasets in the dandi/dandisets repo, not sure how they are related with this.

**Comment by pgleeson** [comment]
Just have the native install to the GHA env action, along with the now preferred "docker NWBE inside docker Datalad" test, and removed the conda test, so closing this.
