### ISSUE TITLE
Add GitHub actions test on installation of datalad, download, regeneration etc.

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/DANDIArchiveShowcase#4]
@anhknguyen96, I've had some issues getting datalad configures on my ubuntu machine to test the scripts. 

Could you look at what needs to be updated in #3 to get this installing and the script(s) tested? I believe it needs `apt install datalad` and a newer version of git-annex

**Comment by anhknguyen96** [comment]
I believe you'd need `pip install datalad-installer` for installation of dependencies, as detailed [here](https://handbook.datalad.org/en/latest/intro/installation.html#using-python-s-package-manager-pip)
